language: node_js
node_js:
  - v5
  - v4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libkrb5-dev
notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/2e21933d-e4f5-4b9f-bc7f-b528da5b7f58
