language: node_js
node_js:
  - v5
  - v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.0-precise
    packages:
      - g++-4.8
      - mongodb-org-server
before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
notifications:
  webhooks:
    - secure: "lL53EOJY1K0P4U7fQxRASd51SG6ihHbrcZJCxUUWU0V3PJe82nlNbARIfOgNpEzu55ZKH0eJT3ILcZg3iGjvhcYPXTvJZTDj+OCS3fBD2CTPwO940xOMJ2WnSAJZ3kJyviJevo9Ha6eFUSJFjinEzQSIeK/ICaXwRLVj55wlyK6i5kGRJLAfZMDHsakvszGFVYPk4JtTi9tt0YFuDkOJljIfmmHmBgzzw6IYVqt3CfUEQ28RRTTCAzI0260e3uNkERiVrDXZLFER3bnqwMKuRGwvX6QYAMG47hEVxZNfh/z15VzsBbp6MuiZgcuMpi7Y/7BtbnL6Kyx+8FeujIk7LdWiGGSQB1ks4pvWBL+uJPo/YrDhMK7tvV/17n/E7qqnqyasSDzmZMk98wP8gnplMAmOMBFc7rA55LnMuvp3HxjmOQoqjpJbA60bcSRvXgmPxNmIYLEjGNtmjxyPf5WqOWaLiGl22Ftp2SNsduTOzvGPIsBMK8+tQvJ0W6B3K8KYiIgz97l/rEtTcoihVP4r8x+flyRYOuMfXP8tMy/ZxG8FLsM6GoH6/b1Ph8tuAuCcR64E6uvkmua5gXAjuCA5p5x3eEdVQcntpUW1w74uY3/IHE5YkwYx4mIuzkqwy7EryNO0bSePcsdchGeEQFaArE3ROF5Ii3KXswJKZWWs77I="
services:
  - mongodb
