language: node_js
node_js:
  - v5
  - v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/2e21933d-e4f5-4b9f-bc7f-b528da5b7f58
